let now = new Date();
console.log(now);
console.log(now.getDay());
console.log(now.getMonth() + 1);
console.log(now.getDate());
console.log(now.getFullYear());
console.log(now.getHours());
console.log(now.getMinutes());
console.log(now.getSeconds());
console.log(now.getMilliseconds());
console.log(now.getTime());
